local syntax = require('gearbot.palette').syntax

return {
  Comment = { fg = syntax._comment },
  Constant = { fg = syntax._constant },
  String = { fg = syntax._string },
  Character = { fg = syntax._character },
  Number = { fg = syntax._number },
  Boolean = { fg = syntax._keyword },
  Float = { fg = syntax._number },
  Identifier = { fg = syntax._variable },
  Function = { fg = syntax._function },
  Statement = {},
  Conditional = { fg = syntax._control },
  Repeat = { fg = syntax._control },
  Label = {},
  Operator = { fg = syntax._symbol },
  Keyword = { fg = syntax._keyword },
  Exception = { fg = syntax._keyword },
  PreProc = { fg = syntax._annotation },
  Include = { fg = syntax._keyword },
  Define = { fg = syntax._keyword },
  Macro = { fg = syntax._annotation },
  PreCondit = {},
  Type = { fg = syntax._type },
  StorageClass = {},
  Structure = {},
  Typedef = {},
  Special = {},
  SpecialChar = {},
  Tag = {},
  Delimiter = { fg = syntax._symbol },
  SpecialComment = {},
  Debug = {},
}
