local ui = require('gearbot.palette').ui
local syntax = require('gearbot.palette').syntax

return {
  MiniClueBorder = { fg = ui.border, bg = ui.background },
  MiniClueDescGroup = { fg = syntax._variable, bg = nil },
  MiniClueDescSingle = { fg = syntax._variable, bg = nil },
  MiniClueNextKey = { fg = syntax._keyword, bg = nil },
  MiniClueNextKeyWithPostkeys = { fg = syntax._keyword, bg = nil },
  MiniClueSeparator = { fg = ui.indentGuide, bg = nil },
  MiniClueTitle = { fg = syntax._string, bg = nil },

  MiniCompletionActiveParameter = { fg = nil, bg = nil },
  MiniCompletionDeprecated = { fg = nil, bg = nil },
  MiniCompletionInfoBorderOutdated = { fg = nil, bg = nil },

  MiniDiffSignAdd = { fg = nil, bg = nil },
  MiniDiffSignChange = { fg = nil, bg = nil },
  MiniDiffSignDelete = { fg = nil, bg = nil },
  MiniDiffOverAdd = { fg = nil, bg = nil },
  MiniDiffOverChange = { fg = nil, bg = nil },
  MiniDiffOverChangeBuf = { fg = nil, bg = nil },
  MiniDiffOverContext = { fg = nil, bg = nil },
  MiniDiffOverContextBuf = { fg = nil, bg = nil },
  MiniDiffOverDelete = { fg = nil, bg = nil },

  MiniFilesBorder = { fg = ui.border, bg = ui.background },
  MiniFilesBorderModified = { fg = nil, bg = nil },
  MiniFilesCursorLine = { fg = nil, bg = ui.currentLine },
  MiniFilesDirectory = { fg = syntax._variable, bg = nil },
  MiniFilesFile = { fg = ui.text, bg = nil },
  MiniFilesNormal = { fg = ui.text, bg = ui.background },
  MiniFilesTitle = { fg = syntax._variable, bg = nil },
  MiniFilesTitleFocused = { fg = syntax._variable, bg = nil },

  MiniIconsAzure = { fg = syntax._function, bg = nil },
  MiniIconsBlue = { fg = syntax._symbol, bg = nil },
  MiniIconsCyan = { fg = syntax._functionDef, bg = nil },
  MiniIconsGreen = { fg = nil, bg = nil },
  MiniIconsGrey = { fg = ui.text, bg = nil },
  MiniIconsOrange = { fg = syntax._annotation, bg = nil },
  MiniIconsPurple = { fg = syntax._functionBuiltin, bg = nil },
  MiniIconsRed = { fg = syntax._keyword, bg = nil },
  MiniIconsYellow = { fg = syntax._string, bg = nil },

  MiniPickBorder = { fg = ui.border, bg = ui.background },
  MiniPickBorderBusy = { fg = nil, bg = nil },
  MiniPickBorderText = { fg = syntax._comment, bg = ui.background },
  MiniPickCursor = { fg = syntax._string, bg = nil },
  MiniPickIconDirectory = { fg = nil, bg = nil },
  MiniPickIconFile = { fg = nil, bg = nil },
  MiniPickHeader = { fg = nil, bg = nil },
  MiniPickMatchCurrent = { fg = nil, bg = ui.currentLine },
  MiniPickMatchMarked = { fg = nil, bg = nil },
  MiniPickMatchRanges = { fg = syntax._string, bg = nil },
  MiniPickNormal = { fg = ui.text, bg = ui.background },
  MiniPickPreviewLine = { fg = nil, bg = nil },
  MiniPickPreviewRegion = { fg = nil, bg = nil },
  MiniPickPrompt = { fg = syntax._string, bg = ui.background },
  MiniPickPromptCaret = { fg = syntax._string, bg = ui.background },
  MiniPickPromptPrefix = { fg = nil, bg = nil },

  MiniStarterCurrent = { fg = nil, bg = nil },
  MiniStarterFooter = { fg = syntax._comment, bg = nil },
  MiniStarterHeader = { fg = syntax._keyword, bg = nil },
  MiniStarterInactive = { fg = syntax._comment, bg = nil },
  MiniStarterItem = { fg = nil, bg = nil },
  MiniStarterItemBullet = { fg = ui.lineNumber, bg = nil },
  MiniStarterItemPrefix = { fg = nil, bg = nil },
  MiniStarterSection = { fg = syntax._variable, bg = nil },
  MiniStarterQuery = { fg = syntax._string, bg = nil },

  MiniStatuslineModeNormal = { fg = syntax._comment, bg = nil },
  MiniStatuslineModeInsert = { fg = syntax._comment, bg = nil },
  MiniStatuslineModeVisual = { fg = syntax._comment, bg = nil },
  MiniStatuslineModeReplace = { fg = syntax._comment, bg = nil },
  MiniStatuslineModeCommand = { fg = syntax._comment, bg = nil },
  MiniStatuslineModeOther = { fg = syntax._comment, bg = nil },
  MiniStatuslineDevinfo = { fg = syntax._comment, bg = nil },
  MiniStatuslineFilename = { fg = syntax._comment, bg = nil },
  MiniStatuslineFileinfo = { fg = syntax._comment, bg = nil },
  MiniStatuslineInactive = { fg = syntax._comment, bg = nil },

  MiniTablineCurrent = { fg = nil, bg = nil },
  MiniTablineVisible = { fg = nil, bg = nil },
  MiniTablineHidden = { fg = nil, bg = nil },
  MiniTablineModifiedCurrent = { fg = nil, bg = nil },
  MiniTablineModifiedVisible = { fg = nil, bg = nil },
  MiniTablineModifiedHidden = { fg = nil, bg = nil },
  MiniTablineFill = { fg = nil, bg = nil },
  MiniTablineTabpagesection = { fg = nil, bg = nil },
  MiniTablineTrunc = { fg = nil, bg = nil },

  MiniIndentscopeSymbol = { fg = ui.indentGuide, bg = nil },
  MiniIndentscopeSymbolOff = { fg = ui.indentGuide, bg = nil },

  MiniTrailspace = { fg = ui.indentGuide, bg = nil },
}
